# Generated by Django 5.2.9 on 2026-07-13 19:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Bus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operator', models.CharField(max_length=100)),
                ('bus_type', models.CharField(max_length=100)),
                ('from_city', models.CharField(max_length=100)),
                ('to_city', models.CharField(max_length=100)),
                ('price', models.IntegerField()),
                ('departure', models.CharField(max_length=10)),
                ('arrival', models.CharField(max_length=10)),
                ('duration', models.CharField(max_length=20)),
                ('seats_available', models.IntegerField(default=40)),
                ('total_seats', models.IntegerField(default=40)),
                ('amenities', models.TextField(default='')),
                ('eco_friendly', models.BooleanField(default=False)),
                ('is_custom', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True)),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, default='')),
                ('color', models.CharField(default='grad-rose-orange', max_length=100)),
                ('icon', models.CharField(default='🎁', max_length=50)),
                ('percent', models.IntegerField(default=10)),
                ('max_off', models.IntegerField(default=200)),
            ],
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('booking_id', models.CharField(max_length=20, primary_key=True, serialize=False, unique=True)),
                ('bus_name', models.CharField(max_length=100)),
                ('bus_type', models.CharField(max_length=100)),
                ('from_city', models.CharField(max_length=100)),
                ('to_city', models.CharField(max_length=100)),
                ('date', models.CharField(max_length=20)),
                ('departure', models.CharField(max_length=20)),
                ('arrival', models.CharField(max_length=20)),
                ('seats', models.TextField()),
                ('total', models.IntegerField()),
                ('passenger_name', models.CharField(max_length=100)),
                ('passenger_phone', models.CharField(max_length=20)),
                ('passenger_email', models.CharField(max_length=100)),
                ('status', models.CharField(default='confirmed', max_length=20)),
                ('booked_at', models.DateTimeField(auto_now_add=True)),
                ('kind', models.CharField(default='seat', max_length=20)),
                ('km', models.IntegerField(blank=True, null=True)),
                ('fleet_name', models.CharField(blank=True, default='', max_length=100)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bookings', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
